FROM mcr.microsoft.com/windows/servercore:ltsc2019

COPY https://github.com/Freadyuan/iis-docker-eastusdf/blob/master/windowsservercore-ltsc2019new/check-baseimage.ps1 .

RUN powershell -File check-baseimage.ps1
